// <auto-generated />
using System;
using Konveyer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Konveyer.Migrations
{
    [DbContext(typeof(KonveyerDbContext))]
    partial class KonveyerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Konveyer.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Fine")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LimitAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxMonth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Konveyer.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseRegion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientRegion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentRegion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Education")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilialId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportGotCountry")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PassportGotDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportGotRegion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportLetter")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PassportNumber")
                        .HasMaxLength(6)
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PassportPinfl")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("born_in")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Konveyer.Models.Credit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FilialId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PayDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("amount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Credits");
                });
#pragma warning restore 612, 618
        }
    }
}
